from pathlib import Path

from TTS.vits_eval_interface import CONFIG_FILE_NAME, DEFAULT_CHECKPOINT

MODEL_NAME = "vits_tts"
TEXT_INPUT_NAME = "input__0"
SPEAKER_EMBEDDING_INPUT_NAME = "input__1"
AUDIO_SIGNAL_OUTPUT_NAME = "output__0"

MODEL_SE_NAME = "speaker_encoder"
AUDIO_SIGNAL_INPUT_NAME = "input__0"
AUDIO_SIGNAL_SAMPLING_RATE = "input__1"
SPEAKER_EMBEDDING_OUTPUT_NAME = "output__0"

EXPORTED_MODEL_PY_NAME = "model.py"

SERVING_CONFIG_NAME = "serving_config.json"

TTS_CHECKPOINT_DIR_NAME = "tts_checkpoint"
DEFAULT_TTS_CHECKPOINT_NAME = DEFAULT_CHECKPOINT
DEFAULT_TTS_CONFIG_NAME = CONFIG_FILE_NAME

SPEAKER_ENCODER_CHECKPOINT_DIR_NAME = "speaker_checkpoint"
DEFAULT_SPEAKER_ENCODER_CHECKPOINT_NAME = "speaker_encoder.pth.tar"
DEFAULT_SPEAKER_ENCODER_CONFIG_NAME = CONFIG_FILE_NAME

TTS_MODEL_CONFIG_NAME = "config.pbtxt"
SE_MODEL_CONFIG_NAME = "config_se.pbtxt"

TEMPLATE_DIR = Path(__file__).parent / "templates"
TTS_MODEL_CONFIG_TEMPLATE_NAME = "config.pbtxt.template"
SE_MODEL_CONFIG_TEMPLATE_NAME = "config_se.pbtxt.template"

TTS_PYTHON_BACKEND_MODEL_TEMPLATE_NAME = "vits_model_template.py"
SE_PYTHON_BACKEND_MODEL_TEMPLATE_NAME = "se_model_template.py"


TTS_MODEL_CONFIG_TEMPLATE_PATH = TEMPLATE_DIR / TTS_MODEL_CONFIG_TEMPLATE_NAME
SE_MODEL_CONFIG_TEMPLATE_PATH = TEMPLATE_DIR / SE_MODEL_CONFIG_TEMPLATE_NAME

TTS_PYTHON_BACKEND_MODEL_TEMPLATE_PATH = (
        TEMPLATE_DIR / TTS_PYTHON_BACKEND_MODEL_TEMPLATE_NAME
)
SE_PYTHON_BACKEND_MODEL_TEMPLATE_PATH = (
        TEMPLATE_DIR / SE_PYTHON_BACKEND_MODEL_TEMPLATE_NAME
)
