from pathlib import Path

from TTS.vits_eval_interface import CONFIG_FILE_NAME, DEFAULT_CHECKPOINT

MODEL_NAME = "vits_tts"
TEXT_INPUT_NAME = "input__0"
SPEAKER_EMBEDDING_INPUT_NAME = "input__1"
AUDIO_SIGNAL_OUTPUT_NAME = "output__0"

EXPORTED_MODEL_PY_NAME = "model.py"

SERVING_CONFIG_NAME = "serving_config.json"

TTS_CHECKPOINT_DIR_NAME = "tts_checkpoint"
DEFAULT_TTS_CHECKPOINT_NAME = DEFAULT_CHECKPOINT
DEFAULT_TTS_CONFIG_NAME = CONFIG_FILE_NAME

SPEAKER_ENCODER_CHECKPOINT_DIR_NAME = "speaker_checkpoint"
DEFAULT_SPEAKER_ENCODER_CHECKPOINT_NAME = "speaker_encoder.pth.tar"
DEFAULT_SPEAKER_ENCODER_CONFIG_NAME = CONFIG_FILE_NAME

MODEL_CONFIG_NAME = "config.pbtxt"

TEMPLATE_DIR = Path(__file__).parent / "templates"
MODEL_CONFIG_TEMPLATE_NAME = "config.pbtxt.template"
PYTHON_BACKEND_MODEL_TEMPLATE_NAME = "serving_model_template.py"

MODEL_CONFIG_TEMPLATE_PATH = TEMPLATE_DIR / MODEL_CONFIG_TEMPLATE_NAME
PYTHON_BACKEND_MODEL_TEMPLATE_PATH = (
    TEMPLATE_DIR / PYTHON_BACKEND_MODEL_TEMPLATE_NAME
)
